In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [7]:
dependent=dataset[['charges']]

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'splitter':['best','random'],'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
           'max_features':['auto','sqrt','log2']}

grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-3)

grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-3,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
reg=grid.cv_results_
print('The Best R_score Value For The Best Parameter {}:'.format(grid.best_params_))

The Best R_score Value For The Best Parameter {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'}:

In [10]:
Table=pd.DataFrame.from_dict(reg)

In [11]:
Table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010969,0.000488,0.005149,0.000652,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",0.722917,0.607017,0.724018,0.685716,0.692893,0.686512,0.042645,8
1,0.010474,0.001176,0.005451,0.000774,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",0.644253,0.547192,0.670267,0.756642,0.730107,0.669692,0.073299,13
2,0.009630,0.000704,0.005804,0.000514,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.712380,0.661858,0.717024,0.717904,0.737136,0.709260,0.025174,2
3,0.008712,0.000667,0.005265,0.000705,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.749051,0.614258,0.666878,0.605505,0.619294,0.650997,0.053463,15
4,0.006648,0.001679,0.003805,0.000480,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.742391,0.710423,0.629729,0.546685,0.725350,0.670916,0.073160,12
5,0.004838,0.001132,0.002939,0.000855,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.695039,0.592628,0.655794,0.655223,0.617085,0.643154,0.035299,17
6,0.047870,0.009155,0.004807,0.001167,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",0.735150,0.609602,0.719734,0.719267,0.749759,0.706703,0.049838,4
7,0.041105,0.004830,0.004009,0.000631,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",0.696615,0.600581,0.710024,0.720409,0.711166,0.687759,0.044245,7
8,0.032153,0.002195,0.004083,0.000645,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.595321,0.565501,0.526305,0.650414,0.660868,0.599682,0.050772,23
9,0.021730,0.003136,0.004352,0.000384,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.689095,0.570025,0.726657,0.668384,0.755939,0.682020,0.063616,9
10,0.029367,0.001206,0.003901,0.000809,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.650250,0.561812,0.706634,0.733408,0.738037,0.678028,0.065976,10
11,0.024633,0.002793,0.003787,0.000746,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.677826,0.540742,0.707075,0.652136,0.598918,0.635339,0.059175,18
12,0.008795,0.001623,0.004224,0.000865,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.717973,0.656846,0.735465,0.744462,0.676925,0.706334,0.033917,5
13,0.007680,0.001751,0.004347,0.000617,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.710391,0.640236,0.747446,0.685574,0.752775,0.707284,0.041615,3
14,0.008069,0.001318,0.004674,0.000717,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.759805,0.636628,0.726098,0.711229,0.754731,0.717698,0.044338,1
15,0.006866,0.001341,0.004069,0.000833,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.622396,0.556458,0.736530,0.667120,0.679320,0.652365,0.060207,14
16,0.007787,0.001506,0.003566,0.000933,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.722325,0.490163,0.774781,0.659937,0.708507,0.671143,0.097607,11
17,0.007276,0.001106,0.004684,0.000871,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.713164,0.535515,0.566765,0.546085,0.653795,0.603065,0.069026,22
18,0.012310,0.003059,0.004844,0.001192,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",0.721316,0.642601,0.725491,0.743704,0.665530,0.699728,0.038721,6
19,0.007990,0.001707,0.003495,0.000570,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",0.607148,0.579288,0.682100,0.649286,0.725304,0.648625,0.052017,16
20,0.009349,0.001048,0.003486,0.000632,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.629208,0.485118,0.641262,0.619212,0.611709,0.597302,0.056962,24
21,0.006125,0.001384,0.003244,0.001165,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.704084,0.579840,0.654066,0.560238,0.611849,0.622016,0.051887,19
22,0.008128,0.002256,0.003690,0.001004,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.648318,0.553117,0.717256,0.611232,0.553538,0.616692,0.061925,20
23,0.006181,0.001539,0.003689,0.000727,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.675275,0.419783,0.734512,0.535415,0.665041,0.606005,0.113542,21

In [17]:
Age=float(input("Age:"))
BMI=float(input("Bmi:"))
Children=float(input("child:"))
Sex=int(input("sex male 0 or 1 :"))
smoker=int(input("Smoker yes 0 or 1 :"))

Age:38
Bmi:23.1
child:2
sex male 0 or 1 :0
Smoker yes 0 or 1 :0

In [18]:
future_prediction=grid.predict([[Age,BMI,Children,Sex,smoker]])
print("future_prediction ={}".format(future_prediction))

future_prediction =[6686.4313]

C:\Users\Manikandan\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"

In [19]:
import pickle
fileName="Finalized_Model_DR_Gridsearch.sav"

In [15]:
# Save this Model
pickle.dump(grid,open(fileName,'wb'))

In [16]:
# get the Model's predicted Result
Load_Model=pickle.load(open("Finalized_Model_DR_Gridsearch.sav",'rb'))